dist: bionic
language: java
jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential
  
script:
  - cd core/
  - mvn clean package -DskipTests
  - cd ../judge/
  - mvn clean package -DskipTests
  - cd ../sim/
  - mvn clean package -DskipTests
  

after_failure:
  - id
  - ls -al $TRAVIS_BUILD_DIR/hshe/core/target
  - ls -al $TRAVIS_BUILD_DIR/hshe/judge/target
  - ls -al $TRAVIS_BUILD_DIR/hshe/sim/target